# type: ignore
books = [
    {
        "id": 1,
        "title": "The Pragmatic Programmer",
        "author": "Andrew Hunt and David Thomas",
        "publisher": "Addison-Wesley Professional",
        "published_date": "1999-10-20",
        "page_count": 352,
        "language": "en",
    },
    {
        "id": 2,
        "title": "Clean Code",
        "author": "Robert C. Martin",
        "publisher": "Prentice Hall",
        "published_date": "2008-08-01",
        "page_count": 464,
        "language": "en",
    },
    {
        "id": 3,
        "title": "Introduction to Algorithms",
        "author": "Thomas H. Cormen",
        "publisher": "MIT Press",
        "published_date": "2009-07-31",
        "page_count": 1312,
        "language": "en",
    },
    {
        "id": 4,
        "title": "You Don't Know JS: Scope & Closures",
        "author": "Kyle Simpson",
        "publisher": "O'Reilly Media",
        "published_date": "2014-03-20",
        "page_count": 98,
        "language": "en",
    },
    {
        "id": 5,
        "title": "The Alchemist",
        "author": "Paulo Coelho",
        "publisher": "HarperOne",
        "published_date": "1993-05-01",
        "page_count": 208,
        "language": "en",
    },
    {
        "id": 6,
        "title": "Atomic Habits",
        "author": "James Clear",
        "publisher": "Penguin Random House",
        "published_date": "2018-10-16",
        "page_count": 320,
        "language": "en",
    },
    {
        "id": 7,
        "title": "Deep Work",
        "author": "Cal Newport",
        "publisher": "Grand Central Publishing",
        "published_date": "2016-01-05",
        "page_count": 304,
        "language": "en",
    },
    {
        "id": 8,
        "title": "Thinking, Fast and Slow",
        "author": "Daniel Kahneman",
        "publisher": "Farrar, Straus and Giroux",
        "published_date": "2011-10-25",
        "page_count": 499,
        "language": "en",
    },
    {
        "id": 9,
        "title": "The Lean Startup",
        "author": "Eric Ries",
        "publisher": "Crown Business",
        "published_date": "2011-09-13",
        "page_count": 336,
        "language": "en",
    },
    {
        "id": 10,
        "title": "Zero to One",
        "author": "Peter Thiel",
        "publisher": "Crown Business",
        "published_date": "2014-09-16",
        "page_count": 224,
        "language": "en",
    },
    {
        "id": 11,
        "title": "The 7 Habits of Highly Effective People",
        "author": "Stephen R. Covey",
        "publisher": "Free Press",
        "published_date": "1989-08-15",
        "page_count": 381,
        "language": "en",
    },
    {
        "id": 12,
        "title": "Educated",
        "author": "Tara Westover",
        "publisher": "Random House",
        "published_date": "2018-02-20",
        "page_count": 352,
        "language": "en",
    },
    {
        "id": 13,
        "title": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "publisher": "Harper",
        "published_date": "2011-01-01",
        "page_count": 443,
        "language": "en",
    },
    {
        "id": 14,
        "title": "The Subtle Art of Not Giving a F*ck",
        "author": "Mark Manson",
        "publisher": "Harper",
        "published_date": "2016-09-13",
        "page_count": 224,
        "language": "en",
    },
    {
        "id": 15,
        "title": "The Four Agreements",
        "author": "Don Miguel Ruiz",
        "publisher": "Amber-Allen Publishing",
        "published_date": "1997-11-07",
        "page_count": 160,
        "language": "en",
    },
]
